default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima39942_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima39942_test

production:
  <<: *default
  database: furima_39942_production
  username: furima_39942
  password: <%= ENV["FURIMA_39942_DATABASE_PASSWORD"] %>
